name: fuick_wallet
description: "Fuick Web3 Wallet App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fuickjs_flutter:
    path: ../../fuickjs_framework/fuickjs_flutter
  cupertino_icons: ^1.0.8
  web3dart: ^2.7.3
  http: ^1.2.0
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0
  solana: ^0.32.0
  crypto: ^3.0.7
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/js/bundle.js
    - assets/js/bundle.qjc
    - assets/js/framework.bundle.js
    - assets/js/framework.bundle.qjc
